### ISSUE TITLE
Cut page crush

### ISSUE THREAD

**Issue by JingxianL** [WheatonCS/Lexos#254] opened 2015-07-12 04:46 UTC
I just installed lexos on a mac that has never installed before following the installation instruction. When I didn't upload anything, and goes to cut page directly, the page will crush and say 
```
File "/Users/Chenjing/Desktop/Lexos-master/managers/utility.py", line 1211, in loadFileManager
fileManager = pickle.load(open(fileManagerPath, 'rb'))
IOError: [Errno 2] No such file or directory: '/tmp/Lexos/S3D0WV7TBEQSBVC0XZ23SYMAUD603N/filemanager.p'
```
I looked into the tmp folder and find that the folder exists, but the there is nothing in there. So filemanager is not created.

**Comment by JingxianL** [comment] 2015-07-12 08:01
reset will be able to fix it, but I am not sure why it happens.

**Comment by chantisnake** [comment] 2015-07-12 09:39
I think this is caused by browser is caching your old session.

When you  go to cut, the filemanager goes into your session folder to load preview.

and the id of the session folder is stored in your session, but your session is the session when you use the online version. so your back-end cannot find the session folder.

If there is no further question, I think we can close this issue.

**Comment by mleblanc321** [comment] 2015-07-12 12:20
since she just installed lexos, i don't think this is from caching an "old" session;  hmm, i think cut (and other pages?) just assume that the filemanager is already there ...

perhaps we should write a "default" filemanager to the session folder at the start of a new session? (this way, some file would be there) ... (??)

**Comment by scottkleinman** [comment] 2015-07-12 17:40
I think we talked about the "default" file manager idea before, but I can't remember the context. On the the other hand, this might not solve Jingxian's problem if the file manager can't be written. I would suggest some experiments like saving a text file in the session folder or creating a short Python script that writes a file to the session folder. This could be a permissions issue.

To address Moses' answer, is it really possible for a local installation to pick up the online session. That has never happened to me before. Or am I misunderstanding your suggestion?

**Comment by JingxianL** [comment] 2015-07-17 11:54
I think I agree with Mark that, since I have never used lexos on this computer there is really nothing caching in that computer to cause the problem. I think if we have a 'default' filemanager, at least the program will be able to file a file and not crash on it. I am not sure if that filemanager could be written or not in that case. 

Also, the local installation does pick up on the online session. If you first work on an online session, and then open a local one, the page for the local version will then crash, and you will have to reset before you can do anything.

**Comment by mleblanc321** [comment] 2015-07-20 13:41
perhaps moses' recent fix to session fixed this?  Jingxian: how are things now?

**Comment by cmccarthy41899** [comment] 2016-05-30 15:44
cannot reproduce this any more, closing this for now. ---Moses

**Closed by cmccarthy41899** 2016-05-30 15:44 UTC
Labels: bug, Cutting
