### ISSUE TITLE
Scrubber: needs loading icon

### ISSUE THREAD

**Issue by mleblanc321** [WheatonCS/Lexos#152] opened 2015-05-26 17:42 UTC
The scrubber interface could also use a progress bar, confirmation of completion, or tally of files scrubbed.
     Reason: when using a stoplist, the scrubbing is the slowest of the preparation processes (e.g., upwards of 15 minutes for a hundred files).  User-experience would be vastly improved with some progress or completion indicator.

**Comment by JingxianL** [comment] 2015-06-17 20:25
finished loading icon on tokenize page, working on cutter and scrubber right now.

**Comment by scottkleinman** [comment] 2015-06-17 20:37
For In the Margins, I have put a spinner icon on every page. Here's a screen shot:
![capture2](https://cloud.githubusercontent.com/assets/1125917/8218131/e3e1009e-14f5-11e5-9eb7-ee4bbdc3a864.JPG)
Let me know if it's helpful to push this functionality to the master branch.

**Comment by JingxianL** [comment] 2015-06-18 15:10
It would be really helpful to push this functionality to the master branch. Thank you.

**Comment by scottkleinman** [comment] 2015-06-18 15:52
OK, I'll try to get that done today.

**Comment by JingxianL** [comment] 2015-06-18 16:19
I am trying to add the loading icon to the cutter page. The problem is that it is not exactly like the tokenize page. If I add the trigger for the icon in lexos.py, the time for the icon to actually show up is too long (It won't show up as soon as I click on the preview or the apply button), and if the process for cutting isn't too slow, you won't be able to see the icon at all.

**Comment by JingxianL** [comment] 2015-06-18 16:27
I put a loading icon for cut, try and see if it works.

**Comment by scottkleinman** [comment] 2015-06-18 16:54
In base.html you can now find the following line under `<div class="container cf">`:

```html
	<!-- Loading icon -->
	<div id="status"><img src="{{ url_for('static', filename='images/loading-spinner.gif') }}?ver={{version}}" alt="Loading..."></div>
```
This places the loading spinner icon on the page, and I've updated the css file to place it in the centre of the screen with `display: none;`. To show the spinner at the beginning of a process, just use `$("status").show()`. At the end of the process, use `$("status").hide()`.

If you want to put a spinner inside of a specific element, it is a little more complicated. You have to make another div like the one above, but with one change. You have to put it inside a container div like this:

```
<div id="dialogStatusContainer">
    <div id="dialog-status"><img src="{{ url_for('static', filename='images/loading-spinner.gif') }}?ver={{version}}" alt="Loading..."></div>
</div>
```
Here's the code I used to show the spinner in a JQuery UI dialog:

```Javascript
    var myDialogContent = $("#myDialog").empty();
     $("#dialog-status").appendTo(myDialogContent);
     $("#dialog-status").css("display", "block");
     $("#myDialog").dialog({
         title: "Loading title...",
      });
```
I start by emptying the dialog of any previous content. Then I append `$("#dialog-status")` (my copy of `$("status") )` to the dialog. For me, `show()` didn't work in the dialog, so I just set the css to `display: block;`, which does the same thing. At this stage, I didn't have a title for the dialog because I was fetching it by Ajax, so I just gave the dialog the boilerplate "Loading title...".

At the end of the process, I used this:

```Javascript
    $("#myDialog").dialog('option', 'title', title); // Update the dialog with the fetched title value
    $("#myDialog").append(content); // Update the dialog with the fetched content value
    $("#dialog-status").hide(); // Hide the spinner icon
    $("#dialog-status").appendTo($("#dialogStatusContainer")); // Move the spinner icon back to its holder
```

**Comment by scottkleinman** [comment] 2015-06-18 17:40
I couldn't get the loading icon you put in to work, so I made some changes and pushed them. It works now. However, I set the page to display the spinner icon I put in base.html just so you can see how it works. I commented out the commands to display your icon. I like your icon better for this purpose (it is larger and blue), but my icon is styled to display in the centre of the screen. You may wish to borrow the styling to get yours centred. I'm reluctant to adjust the size or colour of my icon at this stage since it is used throughout Lexos. This is something we can adjust at a later stage.

**Comment by JingxianL** [comment] 2015-06-18 20:37
I just pulled again, and see that it is working with the cutter page. I think I made it work with my icon, and made it little bigger for the cut page. And I wasn't sure if we really need a loading icon for the upload page. Also, I need to fix when there is no file and click on the button the icon will still show up. 

The other thing I wasn't quite understand is do we need a loading icon for in the margin? if we do, do we want to use two different icon for lexos and for in the margins? 

I am also wondering if we should put the one that I am using into the base template since I think we only need it for prepare and analyze sections (I think the visualize pages have their loading thing, and manage pages doesn't really need one).

**Comment by scottkleinman** [comment] 2015-06-18 20:49
If you duplicated my code in base.html but used `<div id="status-big-blue">`, or something like that, then you could call either icon at will. If you look in the css file, you will see this:

```CSS
#status, #panel-status, #dialog-status {
  width: 34px;
  height: 34px;
  margin: auto;
    position: absolute;
    top: 0; left: 0; bottom: 0; right: 0;
    border: none;
    display: none;
}
#status img, #panel-status img, #dialog-status img {
  width: 32px;
  height: 32px;
}
```
You can add `#status-blue` and `#status-blue img` to these, and the icon will appear in the centre of the screen or whatever element you are placing it in. If you want it to be `#status-big-blue` (that is, if you want the icon to be bigger, add it to the above and then add:

```CSS
#status-big-blue {
  width: __px; // Fill in your desired width + 2
  height: __px; // Fill in your desired height + 2
}
#status-big-blue img {
  width: __px; // Fill in your desired width
  height: __px; // Fill in your desired height
}
```
Regarding your question about In the Margins, right now In the Margins content can be displayed in the side panel or in a JQueryUI dialog. (Neither of these has been pushed to master yet, so I'm sorry that you can't see them.) Since these are smaller areas on the screen, it makes sense to have a smaller icon. At the moment, I don't see why we can't use the blue one you used, but we have the black one just in case. But we can consider making the blue one the default for Lexos.

**Comment by JingxianL** [comment] 2015-06-18 20:55
I think I am almost finished fixing the one for cut, so you could take a look see if it works after I push that change.

**Comment by JingxianL** [comment] 2015-06-18 21:05
Sara was trying the cut page, and she found that, we couldn't really have the icon in the middle of the page since if we are applying cut, the preview on the right side might become terribly long and icon will be done in the middle of the whole page, which you can't really see at all.

**Comment by scottkleinman** [comment] 2015-06-18 21:14
If I understand correctly, the icon is appearing in the middle of the container div, which is below the bottom of the screen when you have lots of cuts. Here are some possible solutions:

1. Modify the `bottom` css property so that the icon is placed only relative to the top (I'd try removing `bottom: 0` to see what happens).

2. Put the previews in a scrollable div so that the bottom of the container remains on the screen. 

3. Go back to your original placement of the icon on the left side of the screen.

4. Same as 2 above, but place the icon in the scrollable div and replace it with the previews once they are generated (probably the most complicated solution to implement).

**Comment by JingxianL** [comment] 2015-06-18 21:25
I think I will add a scrollable div so that it will look better and work better for the icon. It might take a while till I get that fixed.

**Comment by JingxianL** [comment] 2015-06-18 23:46
Since they delete the button in tokenize, the loading icon got messed up. Fix that later.

**Comment by JingxianL** [comment] 2015-06-22 14:25
I got the icon in scrub and cut to work. I will add the scrollable div in. I'll close this issue and open another one for the icons in anaylze page.

**Closed by JingxianL** 2015-06-22 14:25 UTC
