### ISSUE TITLE
upload problem with AncreneWisse.txt

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#232] opened 2015-06-26 16:37 UTC
`AncreneWisse.txt` takes 5.75 second to upload most of the time are spend on the back-end (only 1 ms on the front-end), and this file is not large. 

`pride_and_prejudice.txt` only take 11ms to upload. I am thinking it is probably because of `cardet`

**Comment by chantisnake** [comment] 2015-06-26 16:54
All of the time are spend on `cardet`, because they have to detect the encoding of the entire file. Anyway to optimize that?

**Comment by scottkleinman** [comment] 2015-06-26 16:57
I think I can confirm that. The encoding of `pride_and_prejudice.txt` is UTF-8, whereas the encoding of `AncreneWisse.txt` is UTF-8 without BOM. In the former case, chardet returns a result immediately, whereas in the latter case, it has to start searching around for high-bit characters ([https://chardet.readthedocs.org/en/latest/how-it-works.html#utf-n-with-a-bom](https://chardet.readthedocs.org/en/latest/how-it-works.html#utf-n-with-a-bom)). So the first test would be converting the encoding of `AncreneWisse.txt`.

It may help to [detect encoding incrementally](https://chardet.readthedocs.org/en/latest/usage.html#example-detecting-encoding-incrementally) if we are not already doing so. Alternatively, we could write our own routine to detect specific characters and bypass chardet if they are found.

**Comment by chantisnake** [comment] 2015-06-26 17:05
I have tried, it did not speed up the process at all... sorry.

**Comment by scottkleinman** [comment] 2015-06-26 17:10
I'm assuming that you tried just changing from without BOM to with BOM. Did you try the detect encoding incrementally routine? If that doesn't work, I'd use regex to find "þ", and then bypass chardet if there's a match. If that doesn't work, I don't think chardet is the problem after all.

**Comment by chantisnake** [comment] 2015-06-26 17:15
I don't know how to change from without BOM to with BOM. Can you try to do that? 

This is probably a minor problem I think that people will spend more than 5 seconds to send their file to Lexos.

**Comment by scottkleinman** [comment] 2015-06-26 17:45
I counted 4 seconds to upload it without BOM and 1 second to upload it with BOM, which seems to confirm that the delay is the chardet procedure. However, this was just by counting. You should probably repeat the experiment with whatever method you are using to measure upload times. To change the encoding in Sublime, select File > Save with Encoding > UTF-8 with BOM.

**Comment by mleblanc321** [comment] 2015-06-26 17:58
We check first 500 chars, if fail, we do entire file .... Hmm,
incrementally test?

Just excellent to see this level of profiling, Moses... Nice

On Friday, June 26, 2015, scottkleinman <notifications@github.com> wrote:

> I counted 4 seconds to upload it without BOM and 1 second to upload it
> with BOM, which seems to confirm that the delay is the chardet procedure.
> However, this was just by counting. You should probably repeat the
> experiment with whatever method you are using to measure upload times. To
> change the encoding in Sublime, select File > Save with Encoding > UTF-8
> with BOM.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WheatonCS/Lexos/issues/232#issuecomment-115808014>.
>


-- 
-----------------------------------------------------------------------------
Mark D. LeBlanc, Ph.D.
Professor of Computer Science
Wheaton College, Norton, MA 02766
508.286.3970

http://cs.wheatoncollege.edu/mleblanc
-----------------------------------------------------------------------------

**Comment by scottkleinman** [comment] 2015-06-26 18:03
The first "þ" in *Ancrene Wisse* is character 1774. So that explains it as well. We should definitely try the detect coding incrementally method instead to see if it improves performance. The link I provided also gives code for working with multiple files.

**Comment by chantisnake** [comment] 2015-06-26 19:07
I have put the code in the decoding part, it did not speed up the process significantly.

**Comment by chantisnake** [comment] 2015-06-26 19:08
I have a thought, I don't know whether this will work. we check the encoding type for the first 500 chars, if it do not work, check 500-1000, if not working, check 1000-1500 until it works.

**Comment by scottkleinman** [comment] 2015-06-26 22:07
I tried it as well. I stuck "þ" and a Chinese character at the end of the first line and then ran universal detector on the first 10 lines. It said they were ASCII and then ran the except code on the entire file to load it. I think the reason why the incremental method didn't speed things up is because it didn't detect the encoding properly. I have no idea why. So it might be a good idea to increment by character count, as you suggest.

**Comment by scottkleinman** [comment] 2015-06-27 18:32
As is, uploading UTF-8 without BOM works; it just takes longer. So I'm labelling this issue as an enhancement request.

**Comment by cmccarthy41899** [comment] 2016-05-27 17:55
fixed in commit 30f33bbb17621629cded113ea4763830f6bde128
we increase the `constants.MIN_ENCODING_DETECT` to 5000.

and in commit 97e57a02310b739546ccf24a76f1bffc1789fc9e
we fix a typo in file_manager that also increase the speed of upload.

**Closed by cmccarthy41899** 2016-05-27 17:55 UTC
Labels: enhancement, Upload
