### ISSUE TITLE
website structure

### ISSUE THREAD

**Issue by SocialHulkHogan** [WheatonCS/Lexos#352] opened 2016-06-15 19:30 UTC
Okay this has been bugging me for a while, but now it's causing a problem I don't know how to fix. there should not be two html files that modify the same page. base_prepare.html and cut.html both modify the cut page. If you want a certain group of pages to look the same, you use css. In Firefox, it doesn't recognize whatever weird way cutting options wrapper from cut.html  was added as part of a div from base_prepare. Is there any reason to have base_prepare.html? Also why is it like this at all? While writing this I figured out that jinja is being used to create these frankenstein pages. Apparently firefox and jinja don't play nicely. I need help from Scott to fix this.

**Comment by scottkleinman** [comment] 2016-06-15 19:57
This seems to be related to issue #349. Noting for reference.

The issue isn't Jinja, but Flask. Essentially, these templates "extend" other templates, which is basically a way of saying that they are includes. That was done in the previous version of Lexos in order to re-use the same code. Whether it is an obstruction in the current version is something we can consider. I'll look into what is causing the Firefox issue the next time I pull the code.

**Comment by SocialHulkHogan** [comment] 2016-06-15 20:09
Instead of using Flask to prevent reusing code, it's better to just use a common javascript file to generate the page elements you want, in conjunction with css. It's easier for future developers if there was only one html file per page. I spent the entire first week and a half trying to understand flask (and I thought I had it for the most part) but this particular part of it has always caused me problems, and continues to do so in about a third of what I do. If you can make this work in firefox then the only problem remaining is the added difficulty in understanding front end code. We definitely could be handling this in a more conventional way though which would help front end programmers in the long run.

**Comment by scottkleinman** [comment] 2016-07-14 06:25
This appears to be working now, so closing.

**Closed by scottkleinman** 2016-07-14 06:25 UTC
Labels: Front End, invalid
