### ISSUE TITLE
the select page problem

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#242] opened 2015-06-30 15:49 UTC
On the select page the gui and the backend behave differently on select page, for example when you hit deselect all, the gui indicate that you are only deselecting all the element on the page, but the back end are deselecting all.

for now we add a reload after you deselect all, the problem is that reloading is kind of slow. (this is basically a hard refresh)

if you can think of a better solution please feel free to change. 
(we have tried to render another template when the post is send, but the back-end would not render then template.)

@scottkleinman

**Comment by chantisnake** [comment] 2015-06-30 15:50
Also, if you are adopting the refresh, you probably don't need to deselect on the gui first and then refresh, just refresh is fine.

**Comment by akuisara** [comment] 2015-06-30 15:53
It would also be nice to keep the table config after reloading the page, more specifically, displaying the same number of documents on each page instead of using the default value.

**Comment by scottkleinman** [comment] 2015-06-30 16:08
The Deselect All issue was an oversight on my part; I called an older back-end function for a different front-end behaviour. However, the discrepancy between front end and back end is proving to be a bigger problem. DataTables just does not want to behave. (In essence, the problem is that the author does not support the behaviour we want very well because he has an Editor plugin to handle it. The Editor plugin, of course, is not open source.)

After struggling with it all day yesterday, I have decided to reverse engineer the functionality with a simpler code base. Right now, I have everything but the filtering done (and that can be left out in a pinch). So I really just need to integrate it into the Lexos styling and hook up the Ajax functions. I hope to have that done by the end of the day.

**Comment by scottkleinman** [comment] 2015-07-01 01:38
I have now pushed a new Select page if anyone wants to look at it. You can access it by going to `http://127.0.0.1:5000/manage` (the old page still works). I had a few unexpected problems (like downloading JQuery causing my browser to crash), so I was only able to get the UI taken care of (but I think it looks pretty good). We have unfortunately lost the ability to have the user select how many documents they wish to see per page. The simple table plugin I used to handle sorting does not seem to have a way to re-draw the table dynamically. We can probably restore that function a little later when we have more time.

So for tomorrow, I need to hook up the selection/deselection/deletion behaviours to the back end functions, as well as the context menu functions. I keep track of selected rows in an array (you can see it in the console), and it seems to work pretty well, except for shift-click selections. It only keeps track of the row you first  and last row you click on, not the rows in between. So I have to figure that out tomorrow.

If you're looking at the structure, I kept off my CSS and Javascript in the template file, and all of the JQuery plugins are in `static/js/manage`. Obviously, we'll eventually move some of that code out of the template file.

If anyone wants to help out with any of the tasks described above, give me a shout.

**Comment by JingxianL** [comment] 2015-07-01 22:15
I just discovered an problem that is related to the old select page, and I wasn't sure if it will still have it on the new select page you are working on. On the old select page. if you have 3 files to begin with for example, you set the first one and second one on the list to be active and go to stats page, all two of the files will set to be checked by default. Then if you go back to the select page, and chose the third file to be active and go back to the stats page, you will see that the check all button is on, but the third file isn't checked. I am not sure if this is a problem with stats or with the select page.

**Comment by chantisnake** [comment] 2015-07-01 22:22
the problem @JingxianL mentioned is because of the back-end of stats, not select

**Comment by JingxianL** [comment] 2015-07-01 22:33
I think Mosses fixed this problem, so I am going to close this.

**Comment by JingxianL** [comment] 2015-07-01 22:33
Sorry to close by mistake.

**Comment by scottkleinman** [comment] 2015-07-02 00:30
Update: I have been working all day on getting the shift-click behaviours to work. It's *very* tricky. But it seems to have come together at the end of the day. I am now working on the delete selected function. Then I think I'm ready to hook up the Ajax. Sorry for the delays. Dealing with range selections is harder than I thought it would be. Updates have been pushed.

**Comment by JingxianL** [comment] 2015-07-19 11:31
I just found that apply class-lable isn't working on local version on my chrome browser.

**Comment by scottkleinman** [comment] 2015-07-19 18:40
It's on the server as well. Firefox returns a weird `element not found` error. I'll look into it as soon as I can.

**Comment by scottkleinman** [comment] 2016-05-29 20:04
This issue relates to the Select page before the DataTables upgrade in Lexos-Bootstrap. If are bugs in the new version, we should probably open a new issue.

**Closed by scottkleinman** 2016-05-29 20:04 UTC
Labels: question, Select
