### ISSUE TITLE
Markup tags disrupt scrubbing and tokenization functions

### ISSUE THREAD

**Issue by evanlaferriere** [WheatonCS/Lexos#378] opened 2016-06-24 16:44 UTC
Do we want to have all the tags functionality in the modal? Rn doe files don't get handled through it, and instead just go through the keep corr/foreign tags radio option. Since handle_tags is now better than that, do we want to get rid of the legacy stuff and move it all over to handle_tags?

**Comment by SocialHulkHogan** [comment] 2016-06-24 16:47
dat handling doe

**Comment by scottkleinman** [comment] 2016-06-24 17:03
Yes, I don't think we need a specific set of functions for handling DOE. The new tag wrangling function should cover it.

**Comment by evanlaferriere** [comment] 2016-06-24 17:11
I'm gonna gut it

**Comment by mleblanc321** [comment] 2016-06-24 21:44
(reopening this ISSUE)
well, we need more testing;  i love evan's SELECT ALL in the XML modal and i agree that our current XML scrubbing *should* handle the DOE files, but we can't seem to reproduce the GenAB results, so i'd really like to methodically get us back to working in a state that allows us to reproduce (earlier) GenAB dendrograms;

**Comment by scottkleinman** [comment] 2016-06-24 21:48
Definitely try downloading the scrubbed files and diffing them before you even try clustering...

**Comment by mleblanc321** [comment] 2016-06-25 19:51
hmm, cheng and i are pondering:   regex does not handle embedded tags

given our regex:

``` python
# < [whitespaces] TAG [SPACE attributes]> contents </[whitespaces]TAG>
#       as applied across newlines, (re.MULTILINE), on re.UNICODE, and .* includes newlines (re.DOTALL)
pattern = re.compile("<\s*"+re.escape(tag)+"(\ .+?>|>).+?<\/\s*"+re.escape(tag)+">", re.MULTILINE | re.DOTALL | re.UNICODE)
```

``` xml
<p> 
one
  <p> two  </p>
one_2
</p>
<p>   three
</p>
```
so we know that we really should be doing this via the DOM, iterating over tags and their children;

for now, are we really going to try and do this with regex?   

CASE 1:
matches first instance (not greedy)
``` xml
[<p>] 
one
  <p> two  [</p>]
```
we will match the opening and closing tag with in `[]`, which is wrong 

CASE 2:
If we do match the longest (greedy)
``` xml
[<p>] 
one
  <p> two  </p>
one_2
</p>
<p>   three
[</p>]
```
we will match the opening and closing tag with in `[]`, which is also wrong

**Comment by scottkleinman** [comment] 2016-06-25 20:02
The regex pattern in issue #295 may help to match embedded elements. See issue #350 for a way to parse the text as a tree. One of these options might help.

**Comment by chantisnake** [comment] 2016-06-27 03:02
we have checked couple of source, these regex seems to be not able to pass through any xml validator. (the most powerful one, of course is the one that w3c created: [xml validtor](http://www.w3schools.com/xml/xml_validator.asp))

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<div>
   <div> this </div>
</div>
<div>
</div>
```
so maybe the above is illegal.

I will close this by now.

**Comment by scottkleinman** [comment] 2016-06-27 03:08
XML requires a root element. So the code below will validate:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<root>
<div>
   <div> this </div>
</div>
<div>
</div>
</root>
```

**Comment by chantisnake** [comment] 2016-06-27 03:23
okay... this is next year.

**Comment by scottkleinman** [comment] 2016-07-16 00:39
Tags disrupt both scrubbing and tokenization, and I don't think there's much we can do without a major overhaul. So I think this needs to be labelled for enhancement.

**Comment by chantisnake** [comment] 2016-07-16 22:36
yes, this is definitely on the to do for lexos 3.5 or 4.0

**Comment by mleblanc321** [comment] 2016-07-17 00:25
>(regex is soooooo limited...)
what?  regex is soooooo powerful, but in the hands of children, dangerous :)

**Comment by chantisnake** [comment] 2016-07-17 00:44
well, regex is generated by DFA, which is the least powerful computing machine of all...

**Comment by scottkleinman** [comment] 2016-07-18 06:19
Cheng fixed the tokenization issue for tags in issue #411, so only half this issue is still relevant. Would the same fix work easily for Scrub? If not, we should perhaps open a separate issue for that and label it for "enhancement".

**Comment by chantisnake** [comment] 2016-07-18 07:12
I think a new issue will be nice.

**Comment by scottkleinman** [comment] 2016-07-18 17:35
This issue has been transferred to #449.

**Closed by scottkleinman** 2016-07-18 17:35 UTC
Labels: enhancement, Scrubbing, Tokenization
