### ISSUE TITLE
tokenizer still crash with no active doc

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#424] opened 2016-07-01 15:24 UTC
I don't really know what to say...

It crashes because when sending a get, `cols` are not defined.

see this line: https://github.com/WheatonCS/Lexos/blob/master/lexos.py#L1747

**Comment by scottkleinman** [comment] 2016-07-01 15:44
Hmmm... It's working on my end. Try uploading one file, and then replace `cols` with `<tr><th>Terms</th><th>Filename</th></tr>'. If that works, the problem is coming out of `utility.generateCSVMatrixFromAjax()`. Also, if it works, check if the message in red at the top of the screen is "This tool is still under development". If the message is longer, you don't have the latest code.

**Comment by chantisnake** [comment] 2016-07-01 16:25
okay, I think that maybe the reason

**Comment by chantisnake** [comment] 2016-07-01 20:21
it still crashes for me...

I uses dan and deselected it, the go to tokenize.

**Comment by scottkleinman** [comment] 2016-07-01 20:24
OK, I get this error as well. I'll chase it up.

**Comment by scottkleinman** [comment] 2016-07-01 21:50
This should be fixed now. It will trigger the error modal to tell you that there are no active docs.

**Comment by SocialHulkHogan** [comment] 2016-07-05 17:47
can we close this?

**Comment by scottkleinman** [comment] 2016-07-05 17:54
Yes.

**Closed by scottkleinman** 2016-07-05 17:54 UTC
Labels: bug, Tokenization
