### ISSUE TITLE
unicode decoding issue on rolling windows page.

### ISSUE THREAD

**Issue by SocialHulkHogan** [WheatonCS/Lexos#428] opened 2016-07-05 18:35 UTC
What tools needed utf 8 encoding to work? I changed line 697 of utility.py from  
legendLabels = legendLabels + str(keyWordList[i].encode('utf-8') + "#")

to

legendLabels = legendLabels + str(keyWordList[i].encode('ascii','ignore') + "#")

in order to fix a crash on rolling windows. Will this mess anything up? Please let me know what to test. Kmeans appears to be unaffected and i think that was the big one with encoding problems.

**Comment by chantisnake** [comment] 2016-07-05 18:40
nearly all the tools need utf-8 to work. if this is not with in to function of rolling windows, this is probably not a good idea.

if it is, I would say this is the way to do it unless you don't have any other way.

**Comment by SocialHulkHogan** [comment] 2016-07-05 18:42
Give me an example of something to test

**Comment by SocialHulkHogan** [comment] 2016-07-05 18:44
also it was weird because I think the string we were converting to unicode was already unicode in the debugger before we even called 697

**Comment by chantisnake** [comment] 2016-07-05 18:45
I have read the code, I am afraid that you will break one of our classical example of rolling windows for dan and az.

I will look it up to see the input.

**Comment by SocialHulkHogan** [comment] 2016-07-05 18:45
Oh nvrmind I think this code only applies to rolling windows.

**Comment by SocialHulkHogan** [comment] 2016-07-05 18:46
btw im in the lab if you feel like joining me

**Comment by chantisnake** [comment] 2016-07-05 18:47
I have my own things to do... so, sorry. I saw you in the lab.

I cannot find the original example. I think we need to put that in the readme in dan and az...

**Comment by chantisnake** [comment] 2016-07-05 18:49
it will take me couple of minute to find the example, do not push other commit until that time. Because I think we may need to revert the latest conmit you push.

**Comment by SocialHulkHogan** [comment] 2016-07-05 18:53
I only changed one line, and the commit had another longer, more useful thing. If it really is bad, just ask me to push what it used to be.

**Comment by chantisnake** [comment] 2016-07-05 18:54
I see the bug now.

One of the classic example of lexos is put in dan and then do the string `ð, þ` and then we can see a clear pattern on the part that is suspect to similar to Az

**Comment by chantisnake** [comment] 2016-07-05 18:54
your change will break that.

**Comment by chantisnake** [comment] 2016-07-05 18:55
that is exact why you don't put two things in one commit...

revert that and I will fix that bug.

**Comment by chantisnake** [comment] 2016-07-05 18:56
hum... I have tested that case, seems like it do not break it.

**Comment by chantisnake** [comment] 2016-07-05 18:57
I may need to investgate more on what the code do. I will push a change later to fix the Unicode issue.

**Comment by chantisnake** [comment] 2016-07-05 18:58
I just look at it again = =, sorry, it do breaks.
![capture](https://cloud.githubusercontent.com/assets/10100995/16596223/ec15fe5a-42c0-11e6-933d-15d93e496878.PNG)

on the legend there is nothing displayed.

**Comment by chantisnake** [comment] 2016-07-05 18:59
you don't need to revert that change, I will take care of all of them.

**Comment by SocialHulkHogan** [comment] 2016-07-05 18:59
my change shouldnt cause that result to be different. If I change it back you can't even make the comparrison

**Comment by SocialHulkHogan** [comment] 2016-07-05 19:00
that's weird

**Comment by chantisnake** [comment] 2016-07-05 19:01
I will take care of it.

**Comment by SocialHulkHogan** [comment] 2016-07-05 19:02
are you sure this isn't a scrubbing problem? why does the encoding affect the way the graph is drawn?

**Comment by SocialHulkHogan** [comment] 2016-07-05 19:06
Oh I see on the legend

**Comment by SocialHulkHogan** [comment] 2016-07-05 19:07
I thought you meant the graph is different now. This'll be easy.

**Comment by chantisnake** [comment] 2016-07-05 19:09
seems like all the crash including CSV crash I fixed in prudential center. 
see this issue: https://github.com/WheatonCS/Lexos/issues/413
and this commit: 08e4721445160174ac4936874ba5493c2f06850e

is caused by someone accidentally committed `from __future__ import unicode_literal` = = 
despite I said it is dangerous...

**Comment by SocialHulkHogan** [comment] 2016-07-05 19:11
Oh so the encoding can go back to unicode then? I was just about to solve the issue of special characters not being drawn in the legend.

**Comment by chantisnake** [comment] 2016-07-05 19:13
I am investigating...

**Comment by chantisnake** [comment] 2016-07-05 19:20
I think this commit fixed it for now. https://github.com/WheatonCS/Lexos/commit/0440992e772c6b1115ef6ab7d55538cb206b44f7

I think we need more testing on this.

**Comment by SocialHulkHogan** [comment] 2016-07-05 19:27
Did you test this? Its telling me dan has no þ in a window of 1200

**Comment by SocialHulkHogan** [comment] 2016-07-05 19:28
this isn't really functional

**Comment by SocialHulkHogan** [comment] 2016-07-05 19:30
Just realized that was because I didnt scrub

**Closed** 2016-07-05 19:30 UTC

**Comment by SocialHulkHogan** [comment] 2016-07-05 19:31
nice job I think you are getting the hang of character encoding :+1:

**Comment by chantisnake** [comment] 2016-07-05 19:37
yes, of course, I fight with it on a little bench in prudential center the whole afternoon with the wifi from Microsoft Store...

**Comment by chantisnake** [comment] 2016-07-06 17:54
is it possible to link that parameter with `constants.IS_SERVER`?

and is that a good idea?

**Comment by scottkleinman** [comment] 2016-07-06 18:13
Transferred to issue #431. See there for my reply.
