### ISSUE TITLE
jQuery is failing in visualizations

### ISSUE THREAD

**Issue by SocialHulkHogan** [WheatonCS/Lexos#419] opened 2016-06-30 15:46 UTC
All the visualizations don't work anymore. The console says there is something wrong with dataset.

**Comment by SocialHulkHogan** [comment] 2016-06-30 15:48
Once again, people need to test before pushing :(

**Comment by evanlaferriere** [comment] 2016-06-30 15:48
I also get a "unexpected string" error on bubbleviz

**Comment by SocialHulkHogan** [comment] 2016-06-30 15:50
If these could stop breaking that'd be great

**Comment by evanlaferriere** [comment] 2016-06-30 15:52
Do you know when it broke?

**Comment by SocialHulkHogan** [comment] 2016-06-30 15:54
after 6 pm yesterday

**Comment by chantisnake** [comment] 2016-06-30 15:55
this may help for you to trap where it is:
https://www.kernel.org/pub/software/scm/git/docs/git-bisect.html

**Comment by SocialHulkHogan** [comment] 2016-06-30 16:04
I'm guessing it's not a coincidence that these are all the pages that use jquery broke after the jquery "fix". I'm sorry if I sound negative. It's cool, just needs to be fixed.

**Comment by scottkleinman** [comment] 2016-06-30 16:31
Is this a result of my fix last night for the jQuery UI conflict with Bootstrap tooltips? I'll roll back the code change and see if it makes a difference. Or could it relate to issue #414?

**Comment by SocialHulkHogan** [comment] 2016-06-30 16:33
414 is fixed. I did that yesterday.

**Comment by SocialHulkHogan** [comment] 2016-06-30 16:34
It was unrelated to this. 414 was happening because submit(false) doesn't mean anything

**Comment by scottkleinman** [comment] 2016-06-30 16:51
Agreed. I can't see that any changes were made, but the d3 function just doesn't seem to be reading the dataset. Getting rid of my jQuery UI fix for the active files icon makes no difference.

**Comment by SocialHulkHogan** [comment] 2016-06-30 16:58
It really makes no difference? That's a heart breaker. Are you 100% sure you reversed every ui change and have it back exactly how I had them yesterday?

**Comment by SocialHulkHogan** [comment] 2016-06-30 16:59
They worked perfectly last night before the jquery thing

**Comment by SocialHulkHogan** [comment] 2016-06-30 17:00
did you test if the tools worked before you pushed your change?

**Comment by scottkleinman** [comment] 2016-06-30 17:02
Of course. I'm pretty sure now that the problem is that the dataset is being returned with the Python Unicode `u` prefix. I'm working on a fix now.

**Comment by SocialHulkHogan** [comment] 2016-06-30 17:06
Oh good I'm glad you could look at that and see what's wrong. I wasn't sure what it's supposed to look like.  I was just hoping this would be an easy fix, considering the date.

**Comment by scottkleinman** [comment] 2016-06-30 17:28
OK, this is a two part problem. If I feed the template a json string without those `u` prefixes, I get a URI decode error. This is caused by the attempt to support Unicode using `decodeURIComponent()` discussed in issue #387. If I remove that function and pass the dataset to the template as a string using `json.dumps`, we get a word cloud. However, I suspect this may cause issues with Unicode texts (though there were none with the Middle English text I had loaded). 

I will push this fix in a few minutes so that you can get the graphs working whilst I try a better solution. However, this confirms that the phenomenon is not related to the jQuery UI fix. That really begs the question of why it just showed up now...

**Comment by scottkleinman** [comment] 2016-06-30 17:35
I have pushed the fix for Word Cloud and BubblViz. Multicloud is a little harder because it uses a different function. I'm looking into that.

**Comment by SocialHulkHogan** [comment] 2016-06-30 17:36
How bizarre. I'm going to look through commits see if I can find anything fishy. The timing of this problem makes no sense. What happened in the last 16 hours?

**Comment by scottkleinman** [comment] 2016-06-30 17:40
Well, the good news is that Word Cloud and BubbleViz seem to work with Classical Chinese as is.

**Comment by SocialHulkHogan** [comment] 2016-06-30 17:49
there seems to have recently been some changes in character encoding. At least now we have an explanation and not the oh so discouraging random crash

**Comment by scottkleinman** [comment] 2016-06-30 17:53
I have now pushed the fix for Multicloud. It also works with Classical Chinese, so I think we can be confident about Unicode compatibility. A plus, is that we are now doing it on the back end, which should be faster. Please pull the change, and, if you don't see any further problems, I think we can close this issue.

**Comment by SocialHulkHogan** [comment] 2016-06-30 18:36
you are a beautiful man

**Closed** 2016-06-30 19:03 UTC
