### ISSUE TITLE
Preview messing up xml

### ISSUE THREAD

**Issue by evanlaferriere** [WheatonCS/Lexos#339] opened 2016-06-10 14:40 UTC
### which option did I check

preview scrubbing w/o remove tags
### which file did I use

book.xml
### what the bug looks like

preview gets rid of almost everything, only shows the author's name (from within nested tags)
### how to reproduce it

upload an xml file
### workspace fil

[workspace.zip](https://github.com/WheatonCS/Lexos/files/309168/workspace.zip)

**Comment by evanlaferriere** [comment] 2016-06-10 14:41
it didn't actually remove anything we weren't expecting when we applied scrubbing but the preview was still wrong

**Comment by evanlaferriere** [comment] 2016-06-14 16:33
#327

**Comment by evanlaferriere** [comment] 2016-06-14 16:34
The apply, preview, and when downloaded aren't always the same either

**Comment by chantisnake** [comment] 2016-06-29 22:08
Is this fixed now? I think I push a fix about preview scrub yesterday.

**Comment by scottkleinman** [comment] 2016-06-29 22:10
I haven't tested it (in particular) I haven't tested Evan's comments that the three actions don't produce the same output. But I seem to recall your pushing a fix. I'll try to test.

**Comment by scottkleinman** [comment] 2017-01-26 23:25
I cannot reproduce this bug, so I'm assuming that @chantisnake's fix did the trick.

**Closed by scottkleinman** 2017-01-26 23:25 UTC
Labels: Needs Testing, Scrubbing
