### ISSUE TITLE
<not serious> when uploading empty file, the program give a internal server error

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#168] opened 2015-06-03 00:08 UTC
````fileString = request.data.decode(encodingType) # Grab the file contents, which were encoded/decoded automatically into python's format````

````TypeError: decode() argument 1 must be string, not None````

**Comment by mleblanc321** [comment] 2015-06-05 13:25
let's trap the empty file situation prior to .decode (and put up an error msg on the screen)

**Comment by scottkleinman** [comment] 2015-06-05 14:05
Possibly related, if you got to Select without first uploading a file, you get a 500 Internal Server Error. The replacement Select page I am working on catches this, but we should check whether other pages require data to be in the session.

**Comment by JingxianL** [comment] 2015-06-05 15:25
I will work on the .decode problem, but I am wasn't gettting the error Scott got. And I tried all the other pages, they looked fine even without any files uploaded.

**Comment by Gryphonwastler** [comment] 2015-06-05 16:19
I trapped for the blank file error by checking the length of the file using JS before the POST request gets made.  I also cannot recreate Scott's error, both my local installation as well as the website work just fine if you hit select. It just goes to a blank select page with no previews.

**Comment by JingxianL** [comment] 2015-06-05 21:32
I was working on my laptop this afternoon, I got the same error Scott got error somehow on my computer, but not on the Linux computer in lab this morning. The error come out as:
```
File "/Users/jingxian/Desktop/Lexos/lexos.py", line 101, in select
fileManager = session_functions.loadFileManager() # Usual loading of the FileManager
File "/Users/jingxian/Desktop/Lexos/helpers/session_functions.py", line 88, in loadFileManager
fileManager = pickle.load(open(managerFilePath, 'rb'))
IOError: [Errno 2] No such file or directory: '/tmp/Lexos/07RYF10AJLDEXC6ZTMRYE5VO8PYW3V/filemanager.p'
```
This happens not only with not uploading before going to select page, but to any other pages.
I will look into that later.

**Comment by mleblanc321** [comment] 2015-06-07 13:17
hmm, this seems to the (old) problem with confusion about the current session;  a Reset seems to take care of the problem, but i'm wondering if we must more explicitly check session status (but i'm not sure what this means right now) ... (??)

**Comment by mleblanc321** [comment] 2015-06-07 13:19
perhaps we should make an empty filemanager.p upon starting a new session, even if no files have been uploaded?

**Comment by Gryphonwastler** [comment] 2015-06-08 13:38
It looks like the problem is being caused by a lack of a session folder.  I am able to get this error, but it seems that at least in my case, the filemanager cannot be loaded because the session folder has not been created.  I think this has to do with the @app.route("/") in lexos.py in combination with running locally. It seems that when you type in "localhost:5000/" lexos is either taking you straight to upload and not using @app.route("/") at all or is failing to initialize the session.  My best guess is that since session_functions.init() works just fine in @app.route("/reset") the problem is with the if statement "if 'id' not in session: " which must not be doing what we want it too.  I can't find where 'session' comes from so I'm having a hard time following the problem, or maybe that is the problem.

**Comment by Gryphonwastler** [comment] 2015-06-08 14:08
It looks like if we change that if statement to 
"if not os.path.isdir(os.path.join(constants.UPLOAD_FOLDER , session['id'])):
        session_functions.init()"
then it will work.  I made it so that lexos checks to see if the user's current cookie's session id is a valid directory within "/tmp/Lexos" instead of just checking to see if the cookie had an id in it. 

Jingxian, you may want to test this on your windows box to double check that this is fixing the issue, but I think it should.

**Comment by JingxianL** [comment] 2015-06-08 14:22
Sure, I will check this.

**Comment by JingxianL** [comment] 2015-06-08 19:24
I checked with my computer and it doesn't have the error any more. So I will close this issue.

**Closed by JingxianL** 2015-06-08 19:24 UTC
Labels: bug
